[workspace]

members = [
    "p1_parser",
    "bridge",
]

# Removing 'bridge' from default-members fixes 'cargo build' and 'cargo test',
# because 'bridge' will not compile successfully for the host arch.
default-members = ["p1_parser"]
