[package]
name = "message"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
postcard = "1.0.4"
serde = { version = "1.0.160", features = ["derive"] }
p1_parser = { path = "../p1_parser" }